apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trailhead-production

bases:
  - ../../base

resources:
  - database-ha-postgres.yaml
  - security-networkpolicies.yaml

images:
  - name: quay.io/mkbn02/ui-service
    newName: quay.io/mkbn02/ui-service
    newTag: main
  - name: quay.io/mkbn02/catalogue-service
    newName: quay.io/mkbn02/catalogue-service
    newTag: main
  - name: quay.io/mkbn02/recommendation-service
    newName: quay.io/mkbn02/recommendation-service
    newTag: main
  - name: quay.io/mkbn02/review-service
    newName: quay.io/mkbn02/review-service
    newTag: main

patches:
  - target:
      kind: Service
      group: serving.knative.dev
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations/autoscaling.knative.dev~1min-scale
        value: "1"
