apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trailhead-production

bases:
  - ../../base

resources:
  - database-ha-postgres.yaml
  - security-networkpolicies.yaml

images:
  - name: image-registry.openshift-image-registry.svc:5000/trailhead-staging/ui-service
    newName: image-registry.openshift-image-registry.svc:5000/trailhead-production/ui-service
    newTag: main
  - name: image-registry.openshift-image-registry.svc:5000/trailhead-staging/catalogue-service
    newName: image-registry.openshift-image-registry.svc:5000/trailhead-production/catalogue-service
    newTag: main
  - name: image-registry.openshift-image-registry.svc:5000/trailhead-staging/recommendation-service
    newName: image-registry.openshift-image-registry.svc:5000/trailhead-production/recommendation-service
    newTag: main
  - name: image-registry.openshift-image-registry.svc:5000/trailhead-staging/review-service
    newName: image-registry.openshift-image-registry.svc:5000/trailhead-production/review-service
    newTag: main

patches:
  - target:
      kind: Service
      group: serving.knative.dev
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations/autoscaling.knative.dev~1min-scale
        value: "1"
