apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: catalogue-service
  labels:
    app.kubernetes.io/part-of: trailhead-platform
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/scale-to-zero-pod-retention-period: "90s"
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/trailhead-staging/catalogue-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: SERVICE_VERSION
              value: "1.0.0"
