apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - reviews-db.yaml
  - ui-service-ksvc.yaml
  - catalogue-service-ksvc.yaml
  - recommendation-service-ksvc.yaml
  - review-service-ksvc.yaml
