apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trailhead-staging
bases:
  - ../../base
images:
  - name: image-registry.openshift-image-registry.svc:5000/trailhead-staging/ui-service
    newName: image-registry.openshift-image-registry.svc:5000/trailhead-staging/ui-service
    newTag: "d9510d3a517b6f2f63e57dafd9da241e202a8476"
  - name: image-registry.openshift-image-registry.svc:5000/trailhead-staging/catalogue-service
    newName: image-registry.openshift-image-registry.svc:5000/trailhead-staging/catalogue-service
    newTag: "d9510d3a517b6f2f63e57dafd9da241e202a8476"
  - name: image-registry.openshift-image-registry.svc:5000/trailhead-staging/recommendation-service
    newName: image-registry.openshift-image-registry.svc:5000/trailhead-staging/recommendation-service
    newTag: "d9510d3a517b6f2f63e57dafd9da241e202a8476"
  - name: image-registry.openshift-image-registry.svc:5000/trailhead-staging/review-service
    newName: image-registry.openshift-image-registry.svc:5000/trailhead-staging/review-service
    newTag: "d9510d3a517b6f2f63e57dafd9da241e202a8476"
patches:
  - target:
      kind: Service
      group: serving.knative.dev
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations/autoscaling.knative.dev~1scale-to-zero-pod-retention-period
        value: "90s"
