apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trailhead-staging
bases:
  - ../../base
images:
  - name: image-registry.openshift-image-registry.svc:5000/trailhead-staging/ui-service
    newName: image-registry.openshift-image-registry.svc:5000/trailhead-staging/ui-service
    newTag: "e7eef024ba3b28e4dcac4cc8fb892a287f330ee6"
  - name: image-registry.openshift-image-registry.svc:5000/trailhead-staging/catalogue-service
    newName: image-registry.openshift-image-registry.svc:5000/trailhead-staging/catalogue-service
    newTag: "e7eef024ba3b28e4dcac4cc8fb892a287f330ee6"
  - name: image-registry.openshift-image-registry.svc:5000/trailhead-staging/recommendation-service
    newName: image-registry.openshift-image-registry.svc:5000/trailhead-staging/recommendation-service
    newTag: "e7eef024ba3b28e4dcac4cc8fb892a287f330ee6"
  - name: image-registry.openshift-image-registry.svc:5000/trailhead-staging/review-service
    newName: image-registry.openshift-image-registry.svc:5000/trailhead-staging/review-service
    newTag: "e7eef024ba3b28e4dcac4cc8fb892a287f330ee6"
patches:
  - target:
      kind: Service
      group: serving.knative.dev
    patch: |-
      - op: add
        path: /spec/template/metadata/annotations/autoscaling.knative.dev~1scale-to-zero-pod-retention-period
        value: "90s"
