# SNO Staging Environment Overrides for Trailhead App

global:
  namespace: trailhead-staging
  environment: sno-staging
  registryHost: image-registry.openshift-image-registry.svc:5000/trailhead-staging

# Operators are managed separately via dedicated ArgoCD App (trailhead-operators-app)
operators:
  enabled: false

services:
  enabled: true
  tag: "7a1e0a0b02fa3e8682ce883d3a59b43175bd3b65"

tekton-cicd:
  git:
    appRepoUrl: https://github.com/mkbntech/app-services.git
    gitopsRepoUrl: https://github.com/mkbntech/app-services-gitops.git
    branch: main
